#include "cudnn_oss_b29_aot_bridge.h"

// Generated by python/sm103_cudnn_oss_b29_export.py into the AOT include path.
// CuTe DSL 4.7 emits a module parameter in its inline C wrapper but does not
// reference it. Keep -Werror for our bridge while isolating that generated-code
// warning.
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#endif
#include "katago_sm103_b29_cudnn_swiglu.h"
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#include <new>

struct KatagoCudnnOssB29Context {
  katago_sm103_b29_cudnn_swiglu_Kernel_Module_t module;
  int device;
  bool loaded;
};

namespace {

constexpr int B29Rows = 10469;
constexpr int InputChannels = 384;
constexpr int PackedChannels = 2304;
constexpr int OutputChannels = 1152;

int32_t setStatus(int32_t* status, int32_t value) {
  if(status != nullptr)
    *status = value;
  return value;
}

} // namespace

extern "C" KatagoCudnnOssB29Context* katagoCudnnOssB29Create(
  int device,
  int32_t* status
) {
  setStatus(status,KATAGO_CUDNN_OSS_B29_INVALID_ARGUMENT);
  int deviceCount = 0;
  if(device < 0 || cudaGetDeviceCount(&deviceCount) != cudaSuccess || device >= deviceCount)
    return nullptr;

  int previousDevice = 0;
  if(cudaGetDevice(&previousDevice) != cudaSuccess || cudaSetDevice(device) != cudaSuccess)
    return nullptr;
  KatagoCudnnOssB29Context* context = new(std::nothrow) KatagoCudnnOssB29Context();
  if(context == nullptr) {
    cudaSetDevice(previousDevice);
    return nullptr;
  }
  context->module.module = nullptr;
  context->device = device;
  context->loaded = false;
  katago_sm103_b29_cudnn_swiglu_Kernel_Module_Load(&context->module);
  context->loaded = context->module.module != nullptr;
  cudaSetDevice(previousDevice);
  if(!context->loaded) {
    delete context;
    setStatus(status,KATAGO_CUDNN_OSS_B29_MODULE_LOAD_FAILED);
    return nullptr;
  }
  setStatus(status,KATAGO_CUDNN_OSS_B29_SUCCESS);
  return context;
}

extern "C" void katagoCudnnOssB29Destroy(KatagoCudnnOssB29Context* context) {
  if(context == nullptr)
    return;
  int previousDevice = context->device;
  if(cudaGetDevice(&previousDevice) == cudaSuccess)
    cudaSetDevice(context->device);
  if(context->loaded)
    katago_sm103_b29_cudnn_swiglu_Kernel_Module_Unload(&context->module);
  if(previousDevice != context->device)
    cudaSetDevice(previousDevice);
  delete context;
}

extern "C" int32_t katagoCudnnOssB29Launch(
  KatagoCudnnOssB29Context* context,
  const void* input,
  const void* packedWeights,
  void* ab12Scratch,
  void* output,
  float alpha,
  cudaStream_t stream,
  int rows,
  int inputChannels,
  int packedChannels,
  int outputChannels,
  int usingFP16
) {
  if(context == nullptr || !context->loaded || input == nullptr ||
     packedWeights == nullptr || ab12Scratch == nullptr || output == nullptr ||
     rows != B29Rows || inputChannels != InputChannels ||
     packedChannels != PackedChannels || outputChannels != OutputChannels ||
     usingFP16 != 1)
    return KATAGO_CUDNN_OSS_B29_INVALID_ARGUMENT;

  int currentDevice = -1;
  if(cudaGetDevice(&currentDevice) != cudaSuccess || currentDevice != context->device)
    return KATAGO_CUDNN_OSS_B29_WRONG_DEVICE;

  katago_sm103_b29_cudnn_swiglu_Tensor_a_t a = {const_cast<void*>(input)};
  katago_sm103_b29_cudnn_swiglu_Tensor_b_t b = {const_cast<void*>(packedWeights)};
  katago_sm103_b29_cudnn_swiglu_Tensor_ab12_t ab12 = {ab12Scratch};
  katago_sm103_b29_cudnn_swiglu_Tensor_c_t c = {output};
  return cute_dsl_katago_sm103_b29_cudnn_swiglu_wrapper(
    &context->module,&a,&b,&ab12,&c,alpha,stream
  );
}
