#include "fa4_sm103_b29_aot_bridge.h"

// Generated by python/sm103_generate_flash_attn_b29_native_aot.py into the
// authenticated AOT include path. CuTe DSL emits an unused module parameter.
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#endif
#include "fa4_sm103a_b29_d32_control.h"
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#include <cmath>
#include <new>

struct KatagoFa4Sm103B29Context {
  fa4_sm103a_b29_Kernel_Module_t module;
  int device;
  bool loaded;
};

namespace {

constexpr int Batch = 29;
constexpr int Sequence = 361;
constexpr int Heads = 12;
constexpr int HeadDim = 32;
constexpr int RowChannels = Heads * HeadDim;
constexpr float Scale = 0.1767766952966369f;

void setStatus(int32_t* status, int32_t value) {
  if(status != nullptr)
    *status = value;
}

bool isExactSm103Device(int device) {
  int major = 0;
  int minor = 0;
  return
    cudaDeviceGetAttribute(&major,cudaDevAttrComputeCapabilityMajor,device) == cudaSuccess &&
    cudaDeviceGetAttribute(&minor,cudaDevAttrComputeCapabilityMinor,device) == cudaSuccess &&
    major == 10 && minor == 3;
}

fa4_sm103a_b29_Tensor_mQ_t tensor(const void* pointer) {
  fa4_sm103a_b29_Tensor_mQ_t value = {};
  value.data = const_cast<void*>(pointer);
  value.dynamic_shapes[0] = Batch;
  value.dynamic_shapes[1] = Sequence;
  value.dynamic_shapes[2] = Heads;
  value.dynamic_shapes[3] = HeadDim;
  value.dynamic_strides[0] = (int64_t)Sequence * RowChannels;
  value.dynamic_strides[1] = RowChannels;
  value.dynamic_strides[2] = HeadDim;
  return value;
}

} // namespace

extern "C" KatagoFa4Sm103B29Context* katagoFa4Sm103B29Create(
  int device,
  int32_t* status
) {
  setStatus(status,KATAGO_FA4_SM103_B29_INVALID_ARGUMENT);
  int deviceCount = 0;
  if(device < 0 || cudaGetDeviceCount(&deviceCount) != cudaSuccess ||
     device >= deviceCount || !isExactSm103Device(device)) {
    setStatus(status,KATAGO_FA4_SM103_B29_WRONG_DEVICE);
    return nullptr;
  }

  int previousDevice = 0;
  if(cudaGetDevice(&previousDevice) != cudaSuccess ||
     cudaSetDevice(device) != cudaSuccess)
    return nullptr;
  KatagoFa4Sm103B29Context* context =
    new(std::nothrow) KatagoFa4Sm103B29Context();
  if(context == nullptr) {
    cudaSetDevice(previousDevice);
    return nullptr;
  }
  context->module.module = nullptr;
  context->device = device;
  context->loaded = false;
  fa4_sm103a_b29_Kernel_Module_Load(&context->module);
  context->loaded = context->module.module != nullptr;
  cudaSetDevice(previousDevice);
  if(!context->loaded) {
    delete context;
    setStatus(status,KATAGO_FA4_SM103_B29_MODULE_LOAD_FAILED);
    return nullptr;
  }
  setStatus(status,KATAGO_FA4_SM103_B29_SUCCESS);
  return context;
}

extern "C" void katagoFa4Sm103B29Destroy(
  KatagoFa4Sm103B29Context* context
) {
  if(context == nullptr)
    return;
  int previousDevice = context->device;
  if(cudaGetDevice(&previousDevice) == cudaSuccess)
    cudaSetDevice(context->device);
  if(context->loaded)
    fa4_sm103a_b29_Kernel_Module_Unload(&context->module);
  if(previousDevice != context->device)
    cudaSetDevice(previousDevice);
  delete context;
}

extern "C" int32_t katagoFa4Sm103B29Launch(
  KatagoFa4Sm103B29Context* context,
  const void* q,
  const void* k,
  const void* v,
  const void* mask,
  void* output,
  float scale,
  cudaStream_t stream,
  int batch,
  int sequence,
  int heads,
  int kvHeads,
  int qkHeadDim,
  int vHeadDim,
  int packedQKV,
  int usingFP16
) {
  if(context == nullptr || !context->loaded || q == nullptr || k == nullptr ||
     v == nullptr || output == nullptr || mask != nullptr || batch != Batch ||
     sequence != Sequence || heads != Heads || kvHeads != Heads ||
     qkHeadDim != HeadDim || vHeadDim != HeadDim || packedQKV != 0 ||
     usingFP16 != 1 || std::fabs(scale-Scale) > 1.0e-7f)
    return KATAGO_FA4_SM103_B29_INVALID_ARGUMENT;

  int currentDevice = -1;
  if(cudaGetDevice(&currentDevice) != cudaSuccess ||
     currentDevice != context->device)
    return KATAGO_FA4_SM103_B29_WRONG_DEVICE;

  fa4_sm103a_b29_Tensor_mQ_t qTensor = tensor(q);
  fa4_sm103a_b29_Tensor_mK_t kTensor = {};
  fa4_sm103a_b29_Tensor_mV_t vTensor = {};
  fa4_sm103a_b29_Tensor_mO_t outputTensor = {};
  // The generated tensor ABI is structurally identical for Q/K/V/O.
  kTensor.data = const_cast<void*>(k);
  vTensor.data = const_cast<void*>(v);
  outputTensor.data = output;
  for(int index = 0; index < 4; index++) {
    kTensor.dynamic_shapes[index] = qTensor.dynamic_shapes[index];
    vTensor.dynamic_shapes[index] = qTensor.dynamic_shapes[index];
    outputTensor.dynamic_shapes[index] = qTensor.dynamic_shapes[index];
  }
  for(int index = 0; index < 3; index++) {
    kTensor.dynamic_strides[index] = qTensor.dynamic_strides[index];
    vTensor.dynamic_strides[index] = qTensor.dynamic_strides[index];
    outputTensor.dynamic_strides[index] = qTensor.dynamic_strides[index];
  }

  int32_t status = cute_dsl_fa4_sm103a_b29_wrapper(
    &context->module,&qTensor,&kTensor,&vTensor,&outputTensor,
    scale,Sequence,stream
  );
  if(status != 0 || cudaPeekAtLastError() != cudaSuccess)
    return KATAGO_FA4_SM103_B29_LAUNCH_FAILED;
  return KATAGO_FA4_SM103_B29_SUCCESS;
}
